Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,7 +20,12 @@ jobs:
         run: |
           echo "GITHUB_REF: $GITHUB_REF"
           BRANCH_NAME="${GITHUB_REF#refs/heads/}"
-          echo "Branch Name Extracted: $BRANCH_NAME"
+          echo "Extracted Branch Name: $BRANCH_NAME"
+
+          if [ -z "$BRANCH_NAME" ]; then
+            echo "Error: Branch name is empty!"
+            exit 1
+          fi
 
       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.5.3
